apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: triplan-country-producer
  namespace: triplan
  labels:
    k8s-app: triplan-country-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: triplan-country-producer
        type: application
        service: triplan-country-producer-service
        version: "master"
        owner: "pengyue"
        timestamp: ""
    spec:
      containers:
      - name: triplan
        image: pengyue/triplan-country-producer:latest
        ports:
          - containerPort: 80
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /health-liveness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health-readiness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_NAME
          value: triplan-country-producer
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: app
              key: app-version
        - name: APP_HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: app
              key: app-http-port

        - name: KAFKA_BROKER_IP
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: broker-ip
        - name: KAFKA_BROKER_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: broker-port
        - name: KAFKA_ZOOKEEPER_HOST_IP
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: zookeeper-host-ip
        - name: KAFKA_ZOOKEEPER_HOST_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: zookeeper-host-port

        - name: PRODUCER_NODE_UI_LISTEN_PORT
          valueFrom:
            configMapKeyRef:
              name: country-producer
              key: node-ui-listen-port            
        - name: PRODUCER_LONELY_PLANET_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: country-producer
              key: lonely-planet-base-url
        - name: PRODUCER_KAFKA_COUNTRY_TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: country-producer
              key: kafka-country-topic-name                              
        - name: PRODUCER_COUNTRY_JSON_DATA_FILE
          valueFrom:
            configMapKeyRef:
              name: country-producer
              key: country-json-data-file